// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/trxPocket.proto

// Protobuf Java Version: 4.26.1
package com.api.smtp.proto;

/**
 * Protobuf type {@code com.api.smtp.proto.Payment}
 */
public final class Payment extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.api.smtp.proto.Payment)
    PaymentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Payment.class.getName());
  }
  // Use Payment.newBuilder() to construct.
  private Payment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Payment() {
    referenceNumber_ = "";
    productCode_ = "";
    billerCode_ = "";
    billerName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Payment_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Payment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.api.smtp.proto.Payment.class, com.api.smtp.proto.Payment.Builder.class);
  }

  public static final int REFERENCENUMBER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object referenceNumber_ = "";
  /**
   * <code>string referenceNumber = 1;</code>
   * @return The referenceNumber.
   */
  @java.lang.Override
  public java.lang.String getReferenceNumber() {
    java.lang.Object ref = referenceNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      referenceNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string referenceNumber = 1;</code>
   * @return The bytes for referenceNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReferenceNumberBytes() {
    java.lang.Object ref = referenceNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      referenceNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTCODE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object productCode_ = "";
  /**
   * <code>string productCode = 2;</code>
   * @return The productCode.
   */
  @java.lang.Override
  public java.lang.String getProductCode() {
    java.lang.Object ref = productCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productCode_ = s;
      return s;
    }
  }
  /**
   * <code>string productCode = 2;</code>
   * @return The bytes for productCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductCodeBytes() {
    java.lang.Object ref = productCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BILLERCODE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object billerCode_ = "";
  /**
   * <code>string billerCode = 3;</code>
   * @return The billerCode.
   */
  @java.lang.Override
  public java.lang.String getBillerCode() {
    java.lang.Object ref = billerCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      billerCode_ = s;
      return s;
    }
  }
  /**
   * <code>string billerCode = 3;</code>
   * @return The bytes for billerCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBillerCodeBytes() {
    java.lang.Object ref = billerCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      billerCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BILLERNAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object billerName_ = "";
  /**
   * <code>string billerName = 4;</code>
   * @return The billerName.
   */
  @java.lang.Override
  public java.lang.String getBillerName() {
    java.lang.Object ref = billerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      billerName_ = s;
      return s;
    }
  }
  /**
   * <code>string billerName = 4;</code>
   * @return The bytes for billerName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBillerNameBytes() {
    java.lang.Object ref = billerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      billerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(referenceNumber_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, referenceNumber_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(productCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, productCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(billerCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, billerCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(billerName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, billerName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(referenceNumber_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, referenceNumber_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(productCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, productCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(billerCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, billerCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(billerName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, billerName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.api.smtp.proto.Payment)) {
      return super.equals(obj);
    }
    com.api.smtp.proto.Payment other = (com.api.smtp.proto.Payment) obj;

    if (!getReferenceNumber()
        .equals(other.getReferenceNumber())) return false;
    if (!getProductCode()
        .equals(other.getProductCode())) return false;
    if (!getBillerCode()
        .equals(other.getBillerCode())) return false;
    if (!getBillerName()
        .equals(other.getBillerName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REFERENCENUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getReferenceNumber().hashCode();
    hash = (37 * hash) + PRODUCTCODE_FIELD_NUMBER;
    hash = (53 * hash) + getProductCode().hashCode();
    hash = (37 * hash) + BILLERCODE_FIELD_NUMBER;
    hash = (53 * hash) + getBillerCode().hashCode();
    hash = (37 * hash) + BILLERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBillerName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.api.smtp.proto.Payment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.smtp.proto.Payment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.smtp.proto.Payment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.smtp.proto.Payment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.smtp.proto.Payment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.smtp.proto.Payment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.smtp.proto.Payment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.smtp.proto.Payment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.api.smtp.proto.Payment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.api.smtp.proto.Payment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.api.smtp.proto.Payment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.smtp.proto.Payment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.api.smtp.proto.Payment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.api.smtp.proto.Payment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.api.smtp.proto.Payment)
      com.api.smtp.proto.PaymentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Payment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Payment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.api.smtp.proto.Payment.class, com.api.smtp.proto.Payment.Builder.class);
    }

    // Construct using com.api.smtp.proto.Payment.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      referenceNumber_ = "";
      productCode_ = "";
      billerCode_ = "";
      billerName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Payment_descriptor;
    }

    @java.lang.Override
    public com.api.smtp.proto.Payment getDefaultInstanceForType() {
      return com.api.smtp.proto.Payment.getDefaultInstance();
    }

    @java.lang.Override
    public com.api.smtp.proto.Payment build() {
      com.api.smtp.proto.Payment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.api.smtp.proto.Payment buildPartial() {
      com.api.smtp.proto.Payment result = new com.api.smtp.proto.Payment(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.api.smtp.proto.Payment result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.referenceNumber_ = referenceNumber_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.productCode_ = productCode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.billerCode_ = billerCode_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.billerName_ = billerName_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.api.smtp.proto.Payment) {
        return mergeFrom((com.api.smtp.proto.Payment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.api.smtp.proto.Payment other) {
      if (other == com.api.smtp.proto.Payment.getDefaultInstance()) return this;
      if (!other.getReferenceNumber().isEmpty()) {
        referenceNumber_ = other.referenceNumber_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getProductCode().isEmpty()) {
        productCode_ = other.productCode_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getBillerCode().isEmpty()) {
        billerCode_ = other.billerCode_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getBillerName().isEmpty()) {
        billerName_ = other.billerName_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              referenceNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              productCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              billerCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              billerName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object referenceNumber_ = "";
    /**
     * <code>string referenceNumber = 1;</code>
     * @return The referenceNumber.
     */
    public java.lang.String getReferenceNumber() {
      java.lang.Object ref = referenceNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referenceNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string referenceNumber = 1;</code>
     * @return The bytes for referenceNumber.
     */
    public com.google.protobuf.ByteString
        getReferenceNumberBytes() {
      java.lang.Object ref = referenceNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referenceNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string referenceNumber = 1;</code>
     * @param value The referenceNumber to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      referenceNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string referenceNumber = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReferenceNumber() {
      referenceNumber_ = getDefaultInstance().getReferenceNumber();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string referenceNumber = 1;</code>
     * @param value The bytes for referenceNumber to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      referenceNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object productCode_ = "";
    /**
     * <code>string productCode = 2;</code>
     * @return The productCode.
     */
    public java.lang.String getProductCode() {
      java.lang.Object ref = productCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productCode = 2;</code>
     * @return The bytes for productCode.
     */
    public com.google.protobuf.ByteString
        getProductCodeBytes() {
      java.lang.Object ref = productCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productCode = 2;</code>
     * @param value The productCode to set.
     * @return This builder for chaining.
     */
    public Builder setProductCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      productCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string productCode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductCode() {
      productCode_ = getDefaultInstance().getProductCode();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string productCode = 2;</code>
     * @param value The bytes for productCode to set.
     * @return This builder for chaining.
     */
    public Builder setProductCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      productCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object billerCode_ = "";
    /**
     * <code>string billerCode = 3;</code>
     * @return The billerCode.
     */
    public java.lang.String getBillerCode() {
      java.lang.Object ref = billerCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        billerCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string billerCode = 3;</code>
     * @return The bytes for billerCode.
     */
    public com.google.protobuf.ByteString
        getBillerCodeBytes() {
      java.lang.Object ref = billerCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        billerCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string billerCode = 3;</code>
     * @param value The billerCode to set.
     * @return This builder for chaining.
     */
    public Builder setBillerCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      billerCode_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string billerCode = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBillerCode() {
      billerCode_ = getDefaultInstance().getBillerCode();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string billerCode = 3;</code>
     * @param value The bytes for billerCode to set.
     * @return This builder for chaining.
     */
    public Builder setBillerCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      billerCode_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object billerName_ = "";
    /**
     * <code>string billerName = 4;</code>
     * @return The billerName.
     */
    public java.lang.String getBillerName() {
      java.lang.Object ref = billerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        billerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string billerName = 4;</code>
     * @return The bytes for billerName.
     */
    public com.google.protobuf.ByteString
        getBillerNameBytes() {
      java.lang.Object ref = billerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        billerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string billerName = 4;</code>
     * @param value The billerName to set.
     * @return This builder for chaining.
     */
    public Builder setBillerName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      billerName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string billerName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBillerName() {
      billerName_ = getDefaultInstance().getBillerName();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string billerName = 4;</code>
     * @param value The bytes for billerName to set.
     * @return This builder for chaining.
     */
    public Builder setBillerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      billerName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.api.smtp.proto.Payment)
  }

  // @@protoc_insertion_point(class_scope:com.api.smtp.proto.Payment)
  private static final com.api.smtp.proto.Payment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.api.smtp.proto.Payment();
  }

  public static com.api.smtp.proto.Payment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Payment>
      PARSER = new com.google.protobuf.AbstractParser<Payment>() {
    @java.lang.Override
    public Payment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Payment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Payment> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.api.smtp.proto.Payment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

