// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/trxPocket.proto

// Protobuf Java Version: 4.26.1
package com.api.smtp.proto;

public interface PaymentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.api.smtp.proto.Payment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string referenceNumber = 1;</code>
   * @return The referenceNumber.
   */
  java.lang.String getReferenceNumber();
  /**
   * <code>string referenceNumber = 1;</code>
   * @return The bytes for referenceNumber.
   */
  com.google.protobuf.ByteString
      getReferenceNumberBytes();

  /**
   * <code>string productCode = 2;</code>
   * @return The productCode.
   */
  java.lang.String getProductCode();
  /**
   * <code>string productCode = 2;</code>
   * @return The bytes for productCode.
   */
  com.google.protobuf.ByteString
      getProductCodeBytes();

  /**
   * <code>string billerCode = 3;</code>
   * @return The billerCode.
   */
  java.lang.String getBillerCode();
  /**
   * <code>string billerCode = 3;</code>
   * @return The bytes for billerCode.
   */
  com.google.protobuf.ByteString
      getBillerCodeBytes();

  /**
   * <code>string billerName = 4;</code>
   * @return The billerName.
   */
  java.lang.String getBillerName();
  /**
   * <code>string billerName = 4;</code>
   * @return The bytes for billerName.
   */
  com.google.protobuf.ByteString
      getBillerNameBytes();
}
