// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/trxPocket.proto

// Protobuf Java Version: 4.26.1
package com.api.smtp.proto;

/**
 * Protobuf type {@code com.api.smtp.proto.Pocket}
 */
public final class Pocket extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.api.smtp.proto.Pocket)
    PocketOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Pocket.class.getName());
  }
  // Use Pocket.newBuilder() to construct.
  private Pocket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Pocket() {
    pocketId_ = "";
    pocketType_ = "";
    pocketAccount_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Pocket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Pocket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.api.smtp.proto.Pocket.class, com.api.smtp.proto.Pocket.Builder.class);
  }

  public static final int POCKETID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pocketId_ = "";
  /**
   * <code>string pocketId = 1;</code>
   * @return The pocketId.
   */
  @java.lang.Override
  public java.lang.String getPocketId() {
    java.lang.Object ref = pocketId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pocketId_ = s;
      return s;
    }
  }
  /**
   * <code>string pocketId = 1;</code>
   * @return The bytes for pocketId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPocketIdBytes() {
    java.lang.Object ref = pocketId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pocketId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POCKETTYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pocketType_ = "";
  /**
   * <code>string pocketType = 2;</code>
   * @return The pocketType.
   */
  @java.lang.Override
  public java.lang.String getPocketType() {
    java.lang.Object ref = pocketType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pocketType_ = s;
      return s;
    }
  }
  /**
   * <code>string pocketType = 2;</code>
   * @return The bytes for pocketType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPocketTypeBytes() {
    java.lang.Object ref = pocketType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pocketType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POCKETACCOUNT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pocketAccount_ = "";
  /**
   * <code>string pocketAccount = 3;</code>
   * @return The pocketAccount.
   */
  @java.lang.Override
  public java.lang.String getPocketAccount() {
    java.lang.Object ref = pocketAccount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pocketAccount_ = s;
      return s;
    }
  }
  /**
   * <code>string pocketAccount = 3;</code>
   * @return The bytes for pocketAccount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPocketAccountBytes() {
    java.lang.Object ref = pocketAccount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pocketAccount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pocketId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, pocketId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pocketType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, pocketType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pocketAccount_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, pocketAccount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pocketId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, pocketId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pocketType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, pocketType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pocketAccount_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, pocketAccount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.api.smtp.proto.Pocket)) {
      return super.equals(obj);
    }
    com.api.smtp.proto.Pocket other = (com.api.smtp.proto.Pocket) obj;

    if (!getPocketId()
        .equals(other.getPocketId())) return false;
    if (!getPocketType()
        .equals(other.getPocketType())) return false;
    if (!getPocketAccount()
        .equals(other.getPocketAccount())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POCKETID_FIELD_NUMBER;
    hash = (53 * hash) + getPocketId().hashCode();
    hash = (37 * hash) + POCKETTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPocketType().hashCode();
    hash = (37 * hash) + POCKETACCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getPocketAccount().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.api.smtp.proto.Pocket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.smtp.proto.Pocket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.smtp.proto.Pocket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.smtp.proto.Pocket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.smtp.proto.Pocket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.smtp.proto.Pocket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.smtp.proto.Pocket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.smtp.proto.Pocket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.api.smtp.proto.Pocket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.api.smtp.proto.Pocket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.api.smtp.proto.Pocket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.smtp.proto.Pocket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.api.smtp.proto.Pocket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.api.smtp.proto.Pocket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.api.smtp.proto.Pocket)
      com.api.smtp.proto.PocketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Pocket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Pocket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.api.smtp.proto.Pocket.class, com.api.smtp.proto.Pocket.Builder.class);
    }

    // Construct using com.api.smtp.proto.Pocket.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pocketId_ = "";
      pocketType_ = "";
      pocketAccount_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Pocket_descriptor;
    }

    @java.lang.Override
    public com.api.smtp.proto.Pocket getDefaultInstanceForType() {
      return com.api.smtp.proto.Pocket.getDefaultInstance();
    }

    @java.lang.Override
    public com.api.smtp.proto.Pocket build() {
      com.api.smtp.proto.Pocket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.api.smtp.proto.Pocket buildPartial() {
      com.api.smtp.proto.Pocket result = new com.api.smtp.proto.Pocket(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.api.smtp.proto.Pocket result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pocketId_ = pocketId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pocketType_ = pocketType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pocketAccount_ = pocketAccount_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.api.smtp.proto.Pocket) {
        return mergeFrom((com.api.smtp.proto.Pocket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.api.smtp.proto.Pocket other) {
      if (other == com.api.smtp.proto.Pocket.getDefaultInstance()) return this;
      if (!other.getPocketId().isEmpty()) {
        pocketId_ = other.pocketId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPocketType().isEmpty()) {
        pocketType_ = other.pocketType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPocketAccount().isEmpty()) {
        pocketAccount_ = other.pocketAccount_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pocketId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              pocketType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              pocketAccount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object pocketId_ = "";
    /**
     * <code>string pocketId = 1;</code>
     * @return The pocketId.
     */
    public java.lang.String getPocketId() {
      java.lang.Object ref = pocketId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pocketId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pocketId = 1;</code>
     * @return The bytes for pocketId.
     */
    public com.google.protobuf.ByteString
        getPocketIdBytes() {
      java.lang.Object ref = pocketId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pocketId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pocketId = 1;</code>
     * @param value The pocketId to set.
     * @return This builder for chaining.
     */
    public Builder setPocketId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pocketId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string pocketId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPocketId() {
      pocketId_ = getDefaultInstance().getPocketId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string pocketId = 1;</code>
     * @param value The bytes for pocketId to set.
     * @return This builder for chaining.
     */
    public Builder setPocketIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pocketId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object pocketType_ = "";
    /**
     * <code>string pocketType = 2;</code>
     * @return The pocketType.
     */
    public java.lang.String getPocketType() {
      java.lang.Object ref = pocketType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pocketType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pocketType = 2;</code>
     * @return The bytes for pocketType.
     */
    public com.google.protobuf.ByteString
        getPocketTypeBytes() {
      java.lang.Object ref = pocketType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pocketType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pocketType = 2;</code>
     * @param value The pocketType to set.
     * @return This builder for chaining.
     */
    public Builder setPocketType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pocketType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string pocketType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPocketType() {
      pocketType_ = getDefaultInstance().getPocketType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string pocketType = 2;</code>
     * @param value The bytes for pocketType to set.
     * @return This builder for chaining.
     */
    public Builder setPocketTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pocketType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object pocketAccount_ = "";
    /**
     * <code>string pocketAccount = 3;</code>
     * @return The pocketAccount.
     */
    public java.lang.String getPocketAccount() {
      java.lang.Object ref = pocketAccount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pocketAccount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pocketAccount = 3;</code>
     * @return The bytes for pocketAccount.
     */
    public com.google.protobuf.ByteString
        getPocketAccountBytes() {
      java.lang.Object ref = pocketAccount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pocketAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pocketAccount = 3;</code>
     * @param value The pocketAccount to set.
     * @return This builder for chaining.
     */
    public Builder setPocketAccount(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pocketAccount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string pocketAccount = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPocketAccount() {
      pocketAccount_ = getDefaultInstance().getPocketAccount();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string pocketAccount = 3;</code>
     * @param value The bytes for pocketAccount to set.
     * @return This builder for chaining.
     */
    public Builder setPocketAccountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pocketAccount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.api.smtp.proto.Pocket)
  }

  // @@protoc_insertion_point(class_scope:com.api.smtp.proto.Pocket)
  private static final com.api.smtp.proto.Pocket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.api.smtp.proto.Pocket();
  }

  public static com.api.smtp.proto.Pocket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Pocket>
      PARSER = new com.google.protobuf.AbstractParser<Pocket>() {
    @java.lang.Override
    public Pocket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Pocket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Pocket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.api.smtp.proto.Pocket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

