// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/trxPocket.proto

// Protobuf Java Version: 4.26.1
package com.api.smtp.proto;

public interface PocketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.api.smtp.proto.Pocket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pocketId = 1;</code>
   * @return The pocketId.
   */
  java.lang.String getPocketId();
  /**
   * <code>string pocketId = 1;</code>
   * @return The bytes for pocketId.
   */
  com.google.protobuf.ByteString
      getPocketIdBytes();

  /**
   * <code>string pocketType = 2;</code>
   * @return The pocketType.
   */
  java.lang.String getPocketType();
  /**
   * <code>string pocketType = 2;</code>
   * @return The bytes for pocketType.
   */
  com.google.protobuf.ByteString
      getPocketTypeBytes();

  /**
   * <code>string pocketAccount = 3;</code>
   * @return The pocketAccount.
   */
  java.lang.String getPocketAccount();
  /**
   * <code>string pocketAccount = 3;</code>
   * @return The bytes for pocketAccount.
   */
  com.google.protobuf.ByteString
      getPocketAccountBytes();
}
