// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/trxPocket.proto

// Protobuf Java Version: 4.26.1
package com.api.smtp.proto;

/**
 * Protobuf type {@code com.api.smtp.proto.Transaction}
 */
public final class Transaction extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.api.smtp.proto.Transaction)
    TransactionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Transaction.class.getName());
  }
  // Use Transaction.newBuilder() to construct.
  private Transaction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Transaction() {
    transactionId_ = "";
    transactionType_ = "";
    description_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Transaction_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Transaction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.api.smtp.proto.Transaction.class, com.api.smtp.proto.Transaction.Builder.class);
  }

  private int bitField0_;
  private int toCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object to_;
  public enum ToCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    POCKET(6),
    PAYMENT(7),
    TRANSFER(8),
    TO_NOT_SET(0);
    private final int value;
    private ToCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ToCase valueOf(int value) {
      return forNumber(value);
    }

    public static ToCase forNumber(int value) {
      switch (value) {
        case 6: return POCKET;
        case 7: return PAYMENT;
        case 8: return TRANSFER;
        case 0: return TO_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ToCase
  getToCase() {
    return ToCase.forNumber(
        toCase_);
  }

  public static final int TRANSACTIONID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object transactionId_ = "";
  /**
   * <code>string transactionId = 1;</code>
   * @return The transactionId.
   */
  @java.lang.Override
  public java.lang.String getTransactionId() {
    java.lang.Object ref = transactionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionId_ = s;
      return s;
    }
  }
  /**
   * <code>string transactionId = 1;</code>
   * @return The bytes for transactionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransactionIdBytes() {
    java.lang.Object ref = transactionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTIONTYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object transactionType_ = "";
  /**
   * <code>string transactionType = 2;</code>
   * @return The transactionType.
   */
  @java.lang.Override
  public java.lang.String getTransactionType() {
    java.lang.Object ref = transactionType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionType_ = s;
      return s;
    }
  }
  /**
   * <code>string transactionType = 2;</code>
   * @return The bytes for transactionType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransactionTypeBytes() {
    java.lang.Object ref = transactionType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 3;
  private long amount_ = 0L;
  /**
   * <code>int64 amount = 3;</code>
   * @return The amount.
   */
  @java.lang.Override
  public long getAmount() {
    return amount_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }

  public static final int FROM_FIELD_NUMBER = 5;
  private com.api.smtp.proto.Pocket from_;
  /**
   * <code>.com.api.smtp.proto.Pocket from = 5;</code>
   * @return Whether the from field is set.
   */
  @java.lang.Override
  public boolean hasFrom() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.com.api.smtp.proto.Pocket from = 5;</code>
   * @return The from.
   */
  @java.lang.Override
  public com.api.smtp.proto.Pocket getFrom() {
    return from_ == null ? com.api.smtp.proto.Pocket.getDefaultInstance() : from_;
  }
  /**
   * <code>.com.api.smtp.proto.Pocket from = 5;</code>
   */
  @java.lang.Override
  public com.api.smtp.proto.PocketOrBuilder getFromOrBuilder() {
    return from_ == null ? com.api.smtp.proto.Pocket.getDefaultInstance() : from_;
  }

  public static final int POCKET_FIELD_NUMBER = 6;
  /**
   * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
   * @return Whether the pocket field is set.
   */
  @java.lang.Override
  public boolean hasPocket() {
    return toCase_ == 6;
  }
  /**
   * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
   * @return The pocket.
   */
  @java.lang.Override
  public com.api.smtp.proto.Pocket getPocket() {
    if (toCase_ == 6) {
       return (com.api.smtp.proto.Pocket) to_;
    }
    return com.api.smtp.proto.Pocket.getDefaultInstance();
  }
  /**
   * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
   */
  @java.lang.Override
  public com.api.smtp.proto.PocketOrBuilder getPocketOrBuilder() {
    if (toCase_ == 6) {
       return (com.api.smtp.proto.Pocket) to_;
    }
    return com.api.smtp.proto.Pocket.getDefaultInstance();
  }

  public static final int PAYMENT_FIELD_NUMBER = 7;
  /**
   * <code>.com.api.smtp.proto.Payment payment = 7;</code>
   * @return Whether the payment field is set.
   */
  @java.lang.Override
  public boolean hasPayment() {
    return toCase_ == 7;
  }
  /**
   * <code>.com.api.smtp.proto.Payment payment = 7;</code>
   * @return The payment.
   */
  @java.lang.Override
  public com.api.smtp.proto.Payment getPayment() {
    if (toCase_ == 7) {
       return (com.api.smtp.proto.Payment) to_;
    }
    return com.api.smtp.proto.Payment.getDefaultInstance();
  }
  /**
   * <code>.com.api.smtp.proto.Payment payment = 7;</code>
   */
  @java.lang.Override
  public com.api.smtp.proto.PaymentOrBuilder getPaymentOrBuilder() {
    if (toCase_ == 7) {
       return (com.api.smtp.proto.Payment) to_;
    }
    return com.api.smtp.proto.Payment.getDefaultInstance();
  }

  public static final int TRANSFER_FIELD_NUMBER = 8;
  /**
   * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
   * @return Whether the transfer field is set.
   */
  @java.lang.Override
  public boolean hasTransfer() {
    return toCase_ == 8;
  }
  /**
   * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
   * @return The transfer.
   */
  @java.lang.Override
  public com.api.smtp.proto.Transfer getTransfer() {
    if (toCase_ == 8) {
       return (com.api.smtp.proto.Transfer) to_;
    }
    return com.api.smtp.proto.Transfer.getDefaultInstance();
  }
  /**
   * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
   */
  @java.lang.Override
  public com.api.smtp.proto.TransferOrBuilder getTransferOrBuilder() {
    if (toCase_ == 8) {
       return (com.api.smtp.proto.Transfer) to_;
    }
    return com.api.smtp.proto.Transfer.getDefaultInstance();
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 9;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 9;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, transactionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, transactionType_);
    }
    if (amount_ != 0L) {
      output.writeInt64(3, amount_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getTimestamp());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getFrom());
    }
    if (toCase_ == 6) {
      output.writeMessage(6, (com.api.smtp.proto.Pocket) to_);
    }
    if (toCase_ == 7) {
      output.writeMessage(7, (com.api.smtp.proto.Payment) to_);
    }
    if (toCase_ == 8) {
      output.writeMessage(8, (com.api.smtp.proto.Transfer) to_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, description_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, transactionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, transactionType_);
    }
    if (amount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, amount_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTimestamp());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getFrom());
    }
    if (toCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.api.smtp.proto.Pocket) to_);
    }
    if (toCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.api.smtp.proto.Payment) to_);
    }
    if (toCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (com.api.smtp.proto.Transfer) to_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, description_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.api.smtp.proto.Transaction)) {
      return super.equals(obj);
    }
    com.api.smtp.proto.Transaction other = (com.api.smtp.proto.Transaction) obj;

    if (!getTransactionId()
        .equals(other.getTransactionId())) return false;
    if (!getTransactionType()
        .equals(other.getTransactionType())) return false;
    if (getAmount()
        != other.getAmount()) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (hasFrom() != other.hasFrom()) return false;
    if (hasFrom()) {
      if (!getFrom()
          .equals(other.getFrom())) return false;
    }
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getToCase().equals(other.getToCase())) return false;
    switch (toCase_) {
      case 6:
        if (!getPocket()
            .equals(other.getPocket())) return false;
        break;
      case 7:
        if (!getPayment()
            .equals(other.getPayment())) return false;
        break;
      case 8:
        if (!getTransfer()
            .equals(other.getTransfer())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRANSACTIONID_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionId().hashCode();
    hash = (37 * hash) + TRANSACTIONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionType().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmount());
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (hasFrom()) {
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
    }
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    switch (toCase_) {
      case 6:
        hash = (37 * hash) + POCKET_FIELD_NUMBER;
        hash = (53 * hash) + getPocket().hashCode();
        break;
      case 7:
        hash = (37 * hash) + PAYMENT_FIELD_NUMBER;
        hash = (53 * hash) + getPayment().hashCode();
        break;
      case 8:
        hash = (37 * hash) + TRANSFER_FIELD_NUMBER;
        hash = (53 * hash) + getTransfer().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.api.smtp.proto.Transaction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.smtp.proto.Transaction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.smtp.proto.Transaction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.smtp.proto.Transaction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.smtp.proto.Transaction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.smtp.proto.Transaction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.smtp.proto.Transaction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.smtp.proto.Transaction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.api.smtp.proto.Transaction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.api.smtp.proto.Transaction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.api.smtp.proto.Transaction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.smtp.proto.Transaction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.api.smtp.proto.Transaction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.api.smtp.proto.Transaction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.api.smtp.proto.Transaction)
      com.api.smtp.proto.TransactionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Transaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.api.smtp.proto.Transaction.class, com.api.smtp.proto.Transaction.Builder.class);
    }

    // Construct using com.api.smtp.proto.Transaction.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTimestampFieldBuilder();
        getFromFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      transactionId_ = "";
      transactionType_ = "";
      amount_ = 0L;
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      from_ = null;
      if (fromBuilder_ != null) {
        fromBuilder_.dispose();
        fromBuilder_ = null;
      }
      if (pocketBuilder_ != null) {
        pocketBuilder_.clear();
      }
      if (paymentBuilder_ != null) {
        paymentBuilder_.clear();
      }
      if (transferBuilder_ != null) {
        transferBuilder_.clear();
      }
      description_ = "";
      toCase_ = 0;
      to_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Transaction_descriptor;
    }

    @java.lang.Override
    public com.api.smtp.proto.Transaction getDefaultInstanceForType() {
      return com.api.smtp.proto.Transaction.getDefaultInstance();
    }

    @java.lang.Override
    public com.api.smtp.proto.Transaction build() {
      com.api.smtp.proto.Transaction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.api.smtp.proto.Transaction buildPartial() {
      com.api.smtp.proto.Transaction result = new com.api.smtp.proto.Transaction(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.api.smtp.proto.Transaction result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.transactionId_ = transactionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.transactionType_ = transactionType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.amount_ = amount_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.timestamp_ = timestampBuilder_ == null
            ? timestamp_
            : timestampBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.from_ = fromBuilder_ == null
            ? from_
            : fromBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.description_ = description_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(com.api.smtp.proto.Transaction result) {
      result.toCase_ = toCase_;
      result.to_ = this.to_;
      if (toCase_ == 6 &&
          pocketBuilder_ != null) {
        result.to_ = pocketBuilder_.build();
      }
      if (toCase_ == 7 &&
          paymentBuilder_ != null) {
        result.to_ = paymentBuilder_.build();
      }
      if (toCase_ == 8 &&
          transferBuilder_ != null) {
        result.to_ = transferBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.api.smtp.proto.Transaction) {
        return mergeFrom((com.api.smtp.proto.Transaction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.api.smtp.proto.Transaction other) {
      if (other == com.api.smtp.proto.Transaction.getDefaultInstance()) return this;
      if (!other.getTransactionId().isEmpty()) {
        transactionId_ = other.transactionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTransactionType().isEmpty()) {
        transactionType_ = other.transactionType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getAmount() != 0L) {
        setAmount(other.getAmount());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.hasFrom()) {
        mergeFrom(other.getFrom());
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      switch (other.getToCase()) {
        case POCKET: {
          mergePocket(other.getPocket());
          break;
        }
        case PAYMENT: {
          mergePayment(other.getPayment());
          break;
        }
        case TRANSFER: {
          mergeTransfer(other.getTransfer());
          break;
        }
        case TO_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              transactionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              transactionType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              amount_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getTimestampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getFromFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getPocketFieldBuilder().getBuilder(),
                  extensionRegistry);
              toCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getPaymentFieldBuilder().getBuilder(),
                  extensionRegistry);
              toCase_ = 7;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getTransferFieldBuilder().getBuilder(),
                  extensionRegistry);
              toCase_ = 8;
              break;
            } // case 66
            case 74: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int toCase_ = 0;
    private java.lang.Object to_;
    public ToCase
        getToCase() {
      return ToCase.forNumber(
          toCase_);
    }

    public Builder clearTo() {
      toCase_ = 0;
      to_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object transactionId_ = "";
    /**
     * <code>string transactionId = 1;</code>
     * @return The transactionId.
     */
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transactionId = 1;</code>
     * @return The bytes for transactionId.
     */
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transactionId = 1;</code>
     * @param value The transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      transactionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string transactionId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionId() {
      transactionId_ = getDefaultInstance().getTransactionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string transactionId = 1;</code>
     * @param value The bytes for transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      transactionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object transactionType_ = "";
    /**
     * <code>string transactionType = 2;</code>
     * @return The transactionType.
     */
    public java.lang.String getTransactionType() {
      java.lang.Object ref = transactionType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transactionType = 2;</code>
     * @return The bytes for transactionType.
     */
    public com.google.protobuf.ByteString
        getTransactionTypeBytes() {
      java.lang.Object ref = transactionType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transactionType = 2;</code>
     * @param value The transactionType to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      transactionType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string transactionType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionType() {
      transactionType_ = getDefaultInstance().getTransactionType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string transactionType = 2;</code>
     * @param value The bytes for transactionType to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      transactionType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long amount_ ;
    /**
     * <code>int64 amount = 3;</code>
     * @return The amount.
     */
    @java.lang.Override
    public long getAmount() {
      return amount_;
    }
    /**
     * <code>int64 amount = 3;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(long value) {

      amount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 amount = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      amount_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
      } else {
        timestampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          timestamp_ != null &&
          timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimestampBuilder().mergeFrom(value);
        } else {
          timestamp_ = value;
        }
      } else {
        timestampBuilder_.mergeFrom(value);
      }
      if (timestamp_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private com.api.smtp.proto.Pocket from_;
    private com.google.protobuf.SingleFieldBuilder<
        com.api.smtp.proto.Pocket, com.api.smtp.proto.Pocket.Builder, com.api.smtp.proto.PocketOrBuilder> fromBuilder_;
    /**
     * <code>.com.api.smtp.proto.Pocket from = 5;</code>
     * @return Whether the from field is set.
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.com.api.smtp.proto.Pocket from = 5;</code>
     * @return The from.
     */
    public com.api.smtp.proto.Pocket getFrom() {
      if (fromBuilder_ == null) {
        return from_ == null ? com.api.smtp.proto.Pocket.getDefaultInstance() : from_;
      } else {
        return fromBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.api.smtp.proto.Pocket from = 5;</code>
     */
    public Builder setFrom(com.api.smtp.proto.Pocket value) {
      if (fromBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        from_ = value;
      } else {
        fromBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Pocket from = 5;</code>
     */
    public Builder setFrom(
        com.api.smtp.proto.Pocket.Builder builderForValue) {
      if (fromBuilder_ == null) {
        from_ = builderForValue.build();
      } else {
        fromBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Pocket from = 5;</code>
     */
    public Builder mergeFrom(com.api.smtp.proto.Pocket value) {
      if (fromBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          from_ != null &&
          from_ != com.api.smtp.proto.Pocket.getDefaultInstance()) {
          getFromBuilder().mergeFrom(value);
        } else {
          from_ = value;
        }
      } else {
        fromBuilder_.mergeFrom(value);
      }
      if (from_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Pocket from = 5;</code>
     */
    public Builder clearFrom() {
      bitField0_ = (bitField0_ & ~0x00000010);
      from_ = null;
      if (fromBuilder_ != null) {
        fromBuilder_.dispose();
        fromBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Pocket from = 5;</code>
     */
    public com.api.smtp.proto.Pocket.Builder getFromBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getFromFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.api.smtp.proto.Pocket from = 5;</code>
     */
    public com.api.smtp.proto.PocketOrBuilder getFromOrBuilder() {
      if (fromBuilder_ != null) {
        return fromBuilder_.getMessageOrBuilder();
      } else {
        return from_ == null ?
            com.api.smtp.proto.Pocket.getDefaultInstance() : from_;
      }
    }
    /**
     * <code>.com.api.smtp.proto.Pocket from = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.api.smtp.proto.Pocket, com.api.smtp.proto.Pocket.Builder, com.api.smtp.proto.PocketOrBuilder> 
        getFromFieldBuilder() {
      if (fromBuilder_ == null) {
        fromBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.api.smtp.proto.Pocket, com.api.smtp.proto.Pocket.Builder, com.api.smtp.proto.PocketOrBuilder>(
                getFrom(),
                getParentForChildren(),
                isClean());
        from_ = null;
      }
      return fromBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.api.smtp.proto.Pocket, com.api.smtp.proto.Pocket.Builder, com.api.smtp.proto.PocketOrBuilder> pocketBuilder_;
    /**
     * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
     * @return Whether the pocket field is set.
     */
    @java.lang.Override
    public boolean hasPocket() {
      return toCase_ == 6;
    }
    /**
     * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
     * @return The pocket.
     */
    @java.lang.Override
    public com.api.smtp.proto.Pocket getPocket() {
      if (pocketBuilder_ == null) {
        if (toCase_ == 6) {
          return (com.api.smtp.proto.Pocket) to_;
        }
        return com.api.smtp.proto.Pocket.getDefaultInstance();
      } else {
        if (toCase_ == 6) {
          return pocketBuilder_.getMessage();
        }
        return com.api.smtp.proto.Pocket.getDefaultInstance();
      }
    }
    /**
     * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
     */
    public Builder setPocket(com.api.smtp.proto.Pocket value) {
      if (pocketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        to_ = value;
        onChanged();
      } else {
        pocketBuilder_.setMessage(value);
      }
      toCase_ = 6;
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
     */
    public Builder setPocket(
        com.api.smtp.proto.Pocket.Builder builderForValue) {
      if (pocketBuilder_ == null) {
        to_ = builderForValue.build();
        onChanged();
      } else {
        pocketBuilder_.setMessage(builderForValue.build());
      }
      toCase_ = 6;
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
     */
    public Builder mergePocket(com.api.smtp.proto.Pocket value) {
      if (pocketBuilder_ == null) {
        if (toCase_ == 6 &&
            to_ != com.api.smtp.proto.Pocket.getDefaultInstance()) {
          to_ = com.api.smtp.proto.Pocket.newBuilder((com.api.smtp.proto.Pocket) to_)
              .mergeFrom(value).buildPartial();
        } else {
          to_ = value;
        }
        onChanged();
      } else {
        if (toCase_ == 6) {
          pocketBuilder_.mergeFrom(value);
        } else {
          pocketBuilder_.setMessage(value);
        }
      }
      toCase_ = 6;
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
     */
    public Builder clearPocket() {
      if (pocketBuilder_ == null) {
        if (toCase_ == 6) {
          toCase_ = 0;
          to_ = null;
          onChanged();
        }
      } else {
        if (toCase_ == 6) {
          toCase_ = 0;
          to_ = null;
        }
        pocketBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
     */
    public com.api.smtp.proto.Pocket.Builder getPocketBuilder() {
      return getPocketFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
     */
    @java.lang.Override
    public com.api.smtp.proto.PocketOrBuilder getPocketOrBuilder() {
      if ((toCase_ == 6) && (pocketBuilder_ != null)) {
        return pocketBuilder_.getMessageOrBuilder();
      } else {
        if (toCase_ == 6) {
          return (com.api.smtp.proto.Pocket) to_;
        }
        return com.api.smtp.proto.Pocket.getDefaultInstance();
      }
    }
    /**
     * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.api.smtp.proto.Pocket, com.api.smtp.proto.Pocket.Builder, com.api.smtp.proto.PocketOrBuilder> 
        getPocketFieldBuilder() {
      if (pocketBuilder_ == null) {
        if (!(toCase_ == 6)) {
          to_ = com.api.smtp.proto.Pocket.getDefaultInstance();
        }
        pocketBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.api.smtp.proto.Pocket, com.api.smtp.proto.Pocket.Builder, com.api.smtp.proto.PocketOrBuilder>(
                (com.api.smtp.proto.Pocket) to_,
                getParentForChildren(),
                isClean());
        to_ = null;
      }
      toCase_ = 6;
      onChanged();
      return pocketBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.api.smtp.proto.Payment, com.api.smtp.proto.Payment.Builder, com.api.smtp.proto.PaymentOrBuilder> paymentBuilder_;
    /**
     * <code>.com.api.smtp.proto.Payment payment = 7;</code>
     * @return Whether the payment field is set.
     */
    @java.lang.Override
    public boolean hasPayment() {
      return toCase_ == 7;
    }
    /**
     * <code>.com.api.smtp.proto.Payment payment = 7;</code>
     * @return The payment.
     */
    @java.lang.Override
    public com.api.smtp.proto.Payment getPayment() {
      if (paymentBuilder_ == null) {
        if (toCase_ == 7) {
          return (com.api.smtp.proto.Payment) to_;
        }
        return com.api.smtp.proto.Payment.getDefaultInstance();
      } else {
        if (toCase_ == 7) {
          return paymentBuilder_.getMessage();
        }
        return com.api.smtp.proto.Payment.getDefaultInstance();
      }
    }
    /**
     * <code>.com.api.smtp.proto.Payment payment = 7;</code>
     */
    public Builder setPayment(com.api.smtp.proto.Payment value) {
      if (paymentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        to_ = value;
        onChanged();
      } else {
        paymentBuilder_.setMessage(value);
      }
      toCase_ = 7;
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Payment payment = 7;</code>
     */
    public Builder setPayment(
        com.api.smtp.proto.Payment.Builder builderForValue) {
      if (paymentBuilder_ == null) {
        to_ = builderForValue.build();
        onChanged();
      } else {
        paymentBuilder_.setMessage(builderForValue.build());
      }
      toCase_ = 7;
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Payment payment = 7;</code>
     */
    public Builder mergePayment(com.api.smtp.proto.Payment value) {
      if (paymentBuilder_ == null) {
        if (toCase_ == 7 &&
            to_ != com.api.smtp.proto.Payment.getDefaultInstance()) {
          to_ = com.api.smtp.proto.Payment.newBuilder((com.api.smtp.proto.Payment) to_)
              .mergeFrom(value).buildPartial();
        } else {
          to_ = value;
        }
        onChanged();
      } else {
        if (toCase_ == 7) {
          paymentBuilder_.mergeFrom(value);
        } else {
          paymentBuilder_.setMessage(value);
        }
      }
      toCase_ = 7;
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Payment payment = 7;</code>
     */
    public Builder clearPayment() {
      if (paymentBuilder_ == null) {
        if (toCase_ == 7) {
          toCase_ = 0;
          to_ = null;
          onChanged();
        }
      } else {
        if (toCase_ == 7) {
          toCase_ = 0;
          to_ = null;
        }
        paymentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Payment payment = 7;</code>
     */
    public com.api.smtp.proto.Payment.Builder getPaymentBuilder() {
      return getPaymentFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.api.smtp.proto.Payment payment = 7;</code>
     */
    @java.lang.Override
    public com.api.smtp.proto.PaymentOrBuilder getPaymentOrBuilder() {
      if ((toCase_ == 7) && (paymentBuilder_ != null)) {
        return paymentBuilder_.getMessageOrBuilder();
      } else {
        if (toCase_ == 7) {
          return (com.api.smtp.proto.Payment) to_;
        }
        return com.api.smtp.proto.Payment.getDefaultInstance();
      }
    }
    /**
     * <code>.com.api.smtp.proto.Payment payment = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.api.smtp.proto.Payment, com.api.smtp.proto.Payment.Builder, com.api.smtp.proto.PaymentOrBuilder> 
        getPaymentFieldBuilder() {
      if (paymentBuilder_ == null) {
        if (!(toCase_ == 7)) {
          to_ = com.api.smtp.proto.Payment.getDefaultInstance();
        }
        paymentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.api.smtp.proto.Payment, com.api.smtp.proto.Payment.Builder, com.api.smtp.proto.PaymentOrBuilder>(
                (com.api.smtp.proto.Payment) to_,
                getParentForChildren(),
                isClean());
        to_ = null;
      }
      toCase_ = 7;
      onChanged();
      return paymentBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.api.smtp.proto.Transfer, com.api.smtp.proto.Transfer.Builder, com.api.smtp.proto.TransferOrBuilder> transferBuilder_;
    /**
     * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
     * @return Whether the transfer field is set.
     */
    @java.lang.Override
    public boolean hasTransfer() {
      return toCase_ == 8;
    }
    /**
     * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
     * @return The transfer.
     */
    @java.lang.Override
    public com.api.smtp.proto.Transfer getTransfer() {
      if (transferBuilder_ == null) {
        if (toCase_ == 8) {
          return (com.api.smtp.proto.Transfer) to_;
        }
        return com.api.smtp.proto.Transfer.getDefaultInstance();
      } else {
        if (toCase_ == 8) {
          return transferBuilder_.getMessage();
        }
        return com.api.smtp.proto.Transfer.getDefaultInstance();
      }
    }
    /**
     * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
     */
    public Builder setTransfer(com.api.smtp.proto.Transfer value) {
      if (transferBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        to_ = value;
        onChanged();
      } else {
        transferBuilder_.setMessage(value);
      }
      toCase_ = 8;
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
     */
    public Builder setTransfer(
        com.api.smtp.proto.Transfer.Builder builderForValue) {
      if (transferBuilder_ == null) {
        to_ = builderForValue.build();
        onChanged();
      } else {
        transferBuilder_.setMessage(builderForValue.build());
      }
      toCase_ = 8;
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
     */
    public Builder mergeTransfer(com.api.smtp.proto.Transfer value) {
      if (transferBuilder_ == null) {
        if (toCase_ == 8 &&
            to_ != com.api.smtp.proto.Transfer.getDefaultInstance()) {
          to_ = com.api.smtp.proto.Transfer.newBuilder((com.api.smtp.proto.Transfer) to_)
              .mergeFrom(value).buildPartial();
        } else {
          to_ = value;
        }
        onChanged();
      } else {
        if (toCase_ == 8) {
          transferBuilder_.mergeFrom(value);
        } else {
          transferBuilder_.setMessage(value);
        }
      }
      toCase_ = 8;
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
     */
    public Builder clearTransfer() {
      if (transferBuilder_ == null) {
        if (toCase_ == 8) {
          toCase_ = 0;
          to_ = null;
          onChanged();
        }
      } else {
        if (toCase_ == 8) {
          toCase_ = 0;
          to_ = null;
        }
        transferBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
     */
    public com.api.smtp.proto.Transfer.Builder getTransferBuilder() {
      return getTransferFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
     */
    @java.lang.Override
    public com.api.smtp.proto.TransferOrBuilder getTransferOrBuilder() {
      if ((toCase_ == 8) && (transferBuilder_ != null)) {
        return transferBuilder_.getMessageOrBuilder();
      } else {
        if (toCase_ == 8) {
          return (com.api.smtp.proto.Transfer) to_;
        }
        return com.api.smtp.proto.Transfer.getDefaultInstance();
      }
    }
    /**
     * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.api.smtp.proto.Transfer, com.api.smtp.proto.Transfer.Builder, com.api.smtp.proto.TransferOrBuilder> 
        getTransferFieldBuilder() {
      if (transferBuilder_ == null) {
        if (!(toCase_ == 8)) {
          to_ = com.api.smtp.proto.Transfer.getDefaultInstance();
        }
        transferBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.api.smtp.proto.Transfer, com.api.smtp.proto.Transfer.Builder, com.api.smtp.proto.TransferOrBuilder>(
                (com.api.smtp.proto.Transfer) to_,
                getParentForChildren(),
                isClean());
        to_ = null;
      }
      toCase_ = 8;
      onChanged();
      return transferBuilder_;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 9;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 9;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 9;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 9;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.api.smtp.proto.Transaction)
  }

  // @@protoc_insertion_point(class_scope:com.api.smtp.proto.Transaction)
  private static final com.api.smtp.proto.Transaction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.api.smtp.proto.Transaction();
  }

  public static com.api.smtp.proto.Transaction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Transaction>
      PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
    @java.lang.Override
    public Transaction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Transaction> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Transaction> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.api.smtp.proto.Transaction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

