// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/trxPocket.proto

// Protobuf Java Version: 4.26.1
package com.api.smtp.proto;

public interface TransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.api.smtp.proto.Transaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transactionId = 1;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transactionId = 1;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>string transactionType = 2;</code>
   * @return The transactionType.
   */
  java.lang.String getTransactionType();
  /**
   * <code>string transactionType = 2;</code>
   * @return The bytes for transactionType.
   */
  com.google.protobuf.ByteString
      getTransactionTypeBytes();

  /**
   * <code>int64 amount = 3;</code>
   * @return The amount.
   */
  long getAmount();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>.com.api.smtp.proto.Pocket from = 5;</code>
   * @return Whether the from field is set.
   */
  boolean hasFrom();
  /**
   * <code>.com.api.smtp.proto.Pocket from = 5;</code>
   * @return The from.
   */
  com.api.smtp.proto.Pocket getFrom();
  /**
   * <code>.com.api.smtp.proto.Pocket from = 5;</code>
   */
  com.api.smtp.proto.PocketOrBuilder getFromOrBuilder();

  /**
   * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
   * @return Whether the pocket field is set.
   */
  boolean hasPocket();
  /**
   * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
   * @return The pocket.
   */
  com.api.smtp.proto.Pocket getPocket();
  /**
   * <code>.com.api.smtp.proto.Pocket pocket = 6;</code>
   */
  com.api.smtp.proto.PocketOrBuilder getPocketOrBuilder();

  /**
   * <code>.com.api.smtp.proto.Payment payment = 7;</code>
   * @return Whether the payment field is set.
   */
  boolean hasPayment();
  /**
   * <code>.com.api.smtp.proto.Payment payment = 7;</code>
   * @return The payment.
   */
  com.api.smtp.proto.Payment getPayment();
  /**
   * <code>.com.api.smtp.proto.Payment payment = 7;</code>
   */
  com.api.smtp.proto.PaymentOrBuilder getPaymentOrBuilder();

  /**
   * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
   * @return Whether the transfer field is set.
   */
  boolean hasTransfer();
  /**
   * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
   * @return The transfer.
   */
  com.api.smtp.proto.Transfer getTransfer();
  /**
   * <code>.com.api.smtp.proto.Transfer transfer = 8;</code>
   */
  com.api.smtp.proto.TransferOrBuilder getTransferOrBuilder();

  /**
   * <code>string description = 9;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 9;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  com.api.smtp.proto.Transaction.ToCase getToCase();
}
