// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/trxPocket.proto

// Protobuf Java Version: 4.26.1
package com.api.smtp.proto;

/**
 * Protobuf type {@code com.api.smtp.proto.Transfer}
 */
public final class Transfer extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.api.smtp.proto.Transfer)
    TransferOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Transfer.class.getName());
  }
  // Use Transfer.newBuilder() to construct.
  private Transfer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Transfer() {
    referenceNumber_ = "";
    bankCode_ = "";
    bankName_ = "";
    accountNumber_ = "";
    accountName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Transfer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Transfer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.api.smtp.proto.Transfer.class, com.api.smtp.proto.Transfer.Builder.class);
  }

  public static final int REFERENCENUMBER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object referenceNumber_ = "";
  /**
   * <code>string referenceNumber = 1;</code>
   * @return The referenceNumber.
   */
  @java.lang.Override
  public java.lang.String getReferenceNumber() {
    java.lang.Object ref = referenceNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      referenceNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string referenceNumber = 1;</code>
   * @return The bytes for referenceNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReferenceNumberBytes() {
    java.lang.Object ref = referenceNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      referenceNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BANKCODE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bankCode_ = "";
  /**
   * <code>string bankCode = 2;</code>
   * @return The bankCode.
   */
  @java.lang.Override
  public java.lang.String getBankCode() {
    java.lang.Object ref = bankCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bankCode_ = s;
      return s;
    }
  }
  /**
   * <code>string bankCode = 2;</code>
   * @return The bytes for bankCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBankCodeBytes() {
    java.lang.Object ref = bankCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bankCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BANKNAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bankName_ = "";
  /**
   * <code>string bankName = 3;</code>
   * @return The bankName.
   */
  @java.lang.Override
  public java.lang.String getBankName() {
    java.lang.Object ref = bankName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bankName_ = s;
      return s;
    }
  }
  /**
   * <code>string bankName = 3;</code>
   * @return The bytes for bankName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBankNameBytes() {
    java.lang.Object ref = bankName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bankName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNTNUMBER_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object accountNumber_ = "";
  /**
   * <code>string accountNumber = 4;</code>
   * @return The accountNumber.
   */
  @java.lang.Override
  public java.lang.String getAccountNumber() {
    java.lang.Object ref = accountNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string accountNumber = 4;</code>
   * @return The bytes for accountNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccountNumberBytes() {
    java.lang.Object ref = accountNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNTNAME_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object accountName_ = "";
  /**
   * <code>string accountName = 5;</code>
   * @return The accountName.
   */
  @java.lang.Override
  public java.lang.String getAccountName() {
    java.lang.Object ref = accountName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountName_ = s;
      return s;
    }
  }
  /**
   * <code>string accountName = 5;</code>
   * @return The bytes for accountName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccountNameBytes() {
    java.lang.Object ref = accountName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(referenceNumber_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, referenceNumber_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bankCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, bankCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bankName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, bankName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountNumber_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, accountNumber_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, accountName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(referenceNumber_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, referenceNumber_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bankCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, bankCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bankName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, bankName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountNumber_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, accountNumber_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, accountName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.api.smtp.proto.Transfer)) {
      return super.equals(obj);
    }
    com.api.smtp.proto.Transfer other = (com.api.smtp.proto.Transfer) obj;

    if (!getReferenceNumber()
        .equals(other.getReferenceNumber())) return false;
    if (!getBankCode()
        .equals(other.getBankCode())) return false;
    if (!getBankName()
        .equals(other.getBankName())) return false;
    if (!getAccountNumber()
        .equals(other.getAccountNumber())) return false;
    if (!getAccountName()
        .equals(other.getAccountName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REFERENCENUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getReferenceNumber().hashCode();
    hash = (37 * hash) + BANKCODE_FIELD_NUMBER;
    hash = (53 * hash) + getBankCode().hashCode();
    hash = (37 * hash) + BANKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBankName().hashCode();
    hash = (37 * hash) + ACCOUNTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getAccountNumber().hashCode();
    hash = (37 * hash) + ACCOUNTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAccountName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.api.smtp.proto.Transfer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.smtp.proto.Transfer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.smtp.proto.Transfer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.smtp.proto.Transfer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.smtp.proto.Transfer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.smtp.proto.Transfer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.smtp.proto.Transfer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.smtp.proto.Transfer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.api.smtp.proto.Transfer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.api.smtp.proto.Transfer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.api.smtp.proto.Transfer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.smtp.proto.Transfer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.api.smtp.proto.Transfer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.api.smtp.proto.Transfer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.api.smtp.proto.Transfer)
      com.api.smtp.proto.TransferOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Transfer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Transfer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.api.smtp.proto.Transfer.class, com.api.smtp.proto.Transfer.Builder.class);
    }

    // Construct using com.api.smtp.proto.Transfer.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      referenceNumber_ = "";
      bankCode_ = "";
      bankName_ = "";
      accountNumber_ = "";
      accountName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.api.smtp.proto.TransactionProto.internal_static_com_api_smtp_proto_Transfer_descriptor;
    }

    @java.lang.Override
    public com.api.smtp.proto.Transfer getDefaultInstanceForType() {
      return com.api.smtp.proto.Transfer.getDefaultInstance();
    }

    @java.lang.Override
    public com.api.smtp.proto.Transfer build() {
      com.api.smtp.proto.Transfer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.api.smtp.proto.Transfer buildPartial() {
      com.api.smtp.proto.Transfer result = new com.api.smtp.proto.Transfer(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.api.smtp.proto.Transfer result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.referenceNumber_ = referenceNumber_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bankCode_ = bankCode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.bankName_ = bankName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.accountNumber_ = accountNumber_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.accountName_ = accountName_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.api.smtp.proto.Transfer) {
        return mergeFrom((com.api.smtp.proto.Transfer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.api.smtp.proto.Transfer other) {
      if (other == com.api.smtp.proto.Transfer.getDefaultInstance()) return this;
      if (!other.getReferenceNumber().isEmpty()) {
        referenceNumber_ = other.referenceNumber_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getBankCode().isEmpty()) {
        bankCode_ = other.bankCode_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getBankName().isEmpty()) {
        bankName_ = other.bankName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAccountNumber().isEmpty()) {
        accountNumber_ = other.accountNumber_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getAccountName().isEmpty()) {
        accountName_ = other.accountName_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              referenceNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              bankCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              bankName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              accountNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              accountName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object referenceNumber_ = "";
    /**
     * <code>string referenceNumber = 1;</code>
     * @return The referenceNumber.
     */
    public java.lang.String getReferenceNumber() {
      java.lang.Object ref = referenceNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referenceNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string referenceNumber = 1;</code>
     * @return The bytes for referenceNumber.
     */
    public com.google.protobuf.ByteString
        getReferenceNumberBytes() {
      java.lang.Object ref = referenceNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referenceNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string referenceNumber = 1;</code>
     * @param value The referenceNumber to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      referenceNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string referenceNumber = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReferenceNumber() {
      referenceNumber_ = getDefaultInstance().getReferenceNumber();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string referenceNumber = 1;</code>
     * @param value The bytes for referenceNumber to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      referenceNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object bankCode_ = "";
    /**
     * <code>string bankCode = 2;</code>
     * @return The bankCode.
     */
    public java.lang.String getBankCode() {
      java.lang.Object ref = bankCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bankCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bankCode = 2;</code>
     * @return The bytes for bankCode.
     */
    public com.google.protobuf.ByteString
        getBankCodeBytes() {
      java.lang.Object ref = bankCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bankCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bankCode = 2;</code>
     * @param value The bankCode to set.
     * @return This builder for chaining.
     */
    public Builder setBankCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bankCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string bankCode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBankCode() {
      bankCode_ = getDefaultInstance().getBankCode();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string bankCode = 2;</code>
     * @param value The bytes for bankCode to set.
     * @return This builder for chaining.
     */
    public Builder setBankCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bankCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object bankName_ = "";
    /**
     * <code>string bankName = 3;</code>
     * @return The bankName.
     */
    public java.lang.String getBankName() {
      java.lang.Object ref = bankName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bankName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bankName = 3;</code>
     * @return The bytes for bankName.
     */
    public com.google.protobuf.ByteString
        getBankNameBytes() {
      java.lang.Object ref = bankName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bankName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bankName = 3;</code>
     * @param value The bankName to set.
     * @return This builder for chaining.
     */
    public Builder setBankName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bankName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string bankName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBankName() {
      bankName_ = getDefaultInstance().getBankName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string bankName = 3;</code>
     * @param value The bytes for bankName to set.
     * @return This builder for chaining.
     */
    public Builder setBankNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bankName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object accountNumber_ = "";
    /**
     * <code>string accountNumber = 4;</code>
     * @return The accountNumber.
     */
    public java.lang.String getAccountNumber() {
      java.lang.Object ref = accountNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accountNumber = 4;</code>
     * @return The bytes for accountNumber.
     */
    public com.google.protobuf.ByteString
        getAccountNumberBytes() {
      java.lang.Object ref = accountNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accountNumber = 4;</code>
     * @param value The accountNumber to set.
     * @return This builder for chaining.
     */
    public Builder setAccountNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      accountNumber_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string accountNumber = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountNumber() {
      accountNumber_ = getDefaultInstance().getAccountNumber();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string accountNumber = 4;</code>
     * @param value The bytes for accountNumber to set.
     * @return This builder for chaining.
     */
    public Builder setAccountNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      accountNumber_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object accountName_ = "";
    /**
     * <code>string accountName = 5;</code>
     * @return The accountName.
     */
    public java.lang.String getAccountName() {
      java.lang.Object ref = accountName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accountName = 5;</code>
     * @return The bytes for accountName.
     */
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accountName = 5;</code>
     * @param value The accountName to set.
     * @return This builder for chaining.
     */
    public Builder setAccountName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      accountName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string accountName = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountName() {
      accountName_ = getDefaultInstance().getAccountName();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string accountName = 5;</code>
     * @param value The bytes for accountName to set.
     * @return This builder for chaining.
     */
    public Builder setAccountNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      accountName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.api.smtp.proto.Transfer)
  }

  // @@protoc_insertion_point(class_scope:com.api.smtp.proto.Transfer)
  private static final com.api.smtp.proto.Transfer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.api.smtp.proto.Transfer();
  }

  public static com.api.smtp.proto.Transfer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Transfer>
      PARSER = new com.google.protobuf.AbstractParser<Transfer>() {
    @java.lang.Override
    public Transfer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Transfer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Transfer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.api.smtp.proto.Transfer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

