// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/trxPocket.proto

// Protobuf Java Version: 4.26.1
package com.api.smtp.proto;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.api.smtp.proto.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>repeated .com.api.smtp.proto.Transaction data = 2;</code>
   */
  java.util.List<com.api.smtp.proto.Transaction> 
      getDataList();
  /**
   * <code>repeated .com.api.smtp.proto.Transaction data = 2;</code>
   */
  com.api.smtp.proto.Transaction getData(int index);
  /**
   * <code>repeated .com.api.smtp.proto.Transaction data = 2;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .com.api.smtp.proto.Transaction data = 2;</code>
   */
  java.util.List<? extends com.api.smtp.proto.TransactionOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .com.api.smtp.proto.Transaction data = 2;</code>
   */
  com.api.smtp.proto.TransactionOrBuilder getDataOrBuilder(
      int index);

  /**
   * <code>int64 totalBalance = 3;</code>
   * @return The totalBalance.
   */
  long getTotalBalance();
}
