// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/trxPocket.proto

// Protobuf Java Version: 4.26.1
package com.api.smtp.proto;

public interface TransferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.api.smtp.proto.Transfer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string referenceNumber = 1;</code>
   * @return The referenceNumber.
   */
  java.lang.String getReferenceNumber();
  /**
   * <code>string referenceNumber = 1;</code>
   * @return The bytes for referenceNumber.
   */
  com.google.protobuf.ByteString
      getReferenceNumberBytes();

  /**
   * <code>string bankCode = 2;</code>
   * @return The bankCode.
   */
  java.lang.String getBankCode();
  /**
   * <code>string bankCode = 2;</code>
   * @return The bytes for bankCode.
   */
  com.google.protobuf.ByteString
      getBankCodeBytes();

  /**
   * <code>string bankName = 3;</code>
   * @return The bankName.
   */
  java.lang.String getBankName();
  /**
   * <code>string bankName = 3;</code>
   * @return The bytes for bankName.
   */
  com.google.protobuf.ByteString
      getBankNameBytes();

  /**
   * <code>string accountNumber = 4;</code>
   * @return The accountNumber.
   */
  java.lang.String getAccountNumber();
  /**
   * <code>string accountNumber = 4;</code>
   * @return The bytes for accountNumber.
   */
  com.google.protobuf.ByteString
      getAccountNumberBytes();

  /**
   * <code>string accountName = 5;</code>
   * @return The accountName.
   */
  java.lang.String getAccountName();
  /**
   * <code>string accountName = 5;</code>
   * @return The bytes for accountName.
   */
  com.google.protobuf.ByteString
      getAccountNameBytes();
}
