// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/trxPocket.proto
// Protobuf Java Version: 4.26.1

package com.api.smtp.proto;

public final class TransactionProto {
  private TransactionProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      TransactionProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_api_smtp_proto_Pocket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_api_smtp_proto_Pocket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_api_smtp_proto_Payment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_api_smtp_proto_Payment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_api_smtp_proto_Transfer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_api_smtp_proto_Transfer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_api_smtp_proto_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_api_smtp_proto_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_api_smtp_proto_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_api_smtp_proto_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/proto/trxPocket.proto\022\022com.ap" +
      "i.smtp.proto\032\037google/protobuf/timestamp." +
      "proto\"E\n\006Pocket\022\020\n\010pocketId\030\001 \001(\t\022\022\n\npoc" +
      "ketType\030\002 \001(\t\022\025\n\rpocketAccount\030\003 \001(\t\"_\n\007" +
      "Payment\022\027\n\017referenceNumber\030\001 \001(\t\022\023\n\013prod" +
      "uctCode\030\002 \001(\t\022\022\n\nbillerCode\030\003 \001(\t\022\022\n\nbil" +
      "lerName\030\004 \001(\t\"s\n\010Transfer\022\027\n\017referenceNu" +
      "mber\030\001 \001(\t\022\020\n\010bankCode\030\002 \001(\t\022\020\n\010bankName" +
      "\030\003 \001(\t\022\025\n\raccountNumber\030\004 \001(\t\022\023\n\013account" +
      "Name\030\005 \001(\t\"\321\002\n\013Transaction\022\025\n\rtransactio" +
      "nId\030\001 \001(\t\022\027\n\017transactionType\030\002 \001(\t\022\016\n\006am" +
      "ount\030\003 \001(\003\022-\n\ttimestamp\030\004 \001(\0132\032.google.p" +
      "rotobuf.Timestamp\022(\n\004from\030\005 \001(\0132\032.com.ap" +
      "i.smtp.proto.Pocket\022,\n\006pocket\030\006 \001(\0132\032.co" +
      "m.api.smtp.proto.PocketH\000\022.\n\007payment\030\007 \001" +
      "(\0132\033.com.api.smtp.proto.PaymentH\000\0220\n\010tra" +
      "nsfer\030\010 \001(\0132\034.com.api.smtp.proto.Transfe" +
      "rH\000\022\023\n\013description\030\t \001(\tB\004\n\002to\"j\n\023Transa" +
      "ctionResponse\022\016\n\006status\030\001 \001(\t\022-\n\004data\030\002 " +
      "\003(\0132\037.com.api.smtp.proto.Transaction\022\024\n\014" +
      "totalBalance\030\003 \001(\003B(\n\022com.api.smtp.proto" +
      "B\020TransactionProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_api_smtp_proto_Pocket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_api_smtp_proto_Pocket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_api_smtp_proto_Pocket_descriptor,
        new java.lang.String[] { "PocketId", "PocketType", "PocketAccount", });
    internal_static_com_api_smtp_proto_Payment_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_api_smtp_proto_Payment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_api_smtp_proto_Payment_descriptor,
        new java.lang.String[] { "ReferenceNumber", "ProductCode", "BillerCode", "BillerName", });
    internal_static_com_api_smtp_proto_Transfer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_api_smtp_proto_Transfer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_api_smtp_proto_Transfer_descriptor,
        new java.lang.String[] { "ReferenceNumber", "BankCode", "BankName", "AccountNumber", "AccountName", });
    internal_static_com_api_smtp_proto_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_api_smtp_proto_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_api_smtp_proto_Transaction_descriptor,
        new java.lang.String[] { "TransactionId", "TransactionType", "Amount", "Timestamp", "From", "Pocket", "Payment", "Transfer", "Description", "To", });
    internal_static_com_api_smtp_proto_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_api_smtp_proto_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_api_smtp_proto_TransactionResponse_descriptor,
        new java.lang.String[] { "Status", "Data", "TotalBalance", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
